<?php
/*
 * Textos en castellano para terminales.php
 */

$titulo = "Base de Datos de Terminales de la Red COMDES";
$termcomdes = "Terminales";
$h1 = "Terminales de la Red COMDES";
$newtab = "Abrir en una nueva pestaña";
$criterios = "Criterios de Selección/Búsqueda";
$resetcrit = "Limpiar Criterios";
$provtxt = "Proveedor";
$tipotxt = "Tipo de Terminal";
$fijo = "Fijo";
$movil = "Móvil";
$movilb = "Móvil Básico";
$movila = "Móvil Avanzado";
$movilg = "Móvil Gateway/ Repeater";
$portatil = "Portátil";
$portatilb = "Portátil Básico";
$portatila = "Portátil Avanzado";
$portatilx = "Portátil ATEX";
$despacho = "Despacho";
$estadotxt = "Estado";
$alta = "Alta";
$baja = "Baja";
$rep = "Reparación";
$txtaut = "Autenticación";
$dotstxt = "Alta en el DOTS";
$llamtxt = "Llamadas individuales";
$llamop2 = "Semi-dúplex";
$llamop3 = "Dúplex";
$llamop4 = "Ambos";
$h4res = "Resultado de la búsqueda";
$nreg = "Nº total de registros";
$regpg = "registros por página";
$todos = "Todos";
$pgtxt = "Página";
$newter = "Nuevo Terminal";
$noreg = "No hay registros";
$detalle = "Detalle";
$issiselec = "ISSI seleccionados";
$campos = array("Flota","Marca","Modelo","Tipo","Proveedor","ISSI","TEI","Mnemónico","Carpeta","Llam. Ind.","DOTS","Aut.","Encriptado");
$thnterm = "Número de Terminales";
$thrango = "Rango de ISSI";
$thllamind = "Llam. Ind.";
$thnserie = "N. Serie";
$thmodelo = "Modelo";
$thtipo = "Tipo";
$thmnemo = "Mnemónico";
$thaut = "Autenticación";
$thenc = "Encripitación";
$thdirip = "Dirección IP";
$thversion = "Versión";
$thfalta = "Fecha Alta";
$thfecha = "Fecha";
$thobserv = "Observaciones";
$thnumk = "Número K";
$thprov = "Proveedor";
$thcodhw = "Código HW";
$txtdescarga = "Descargar todos";
$permno = "Ni dúplex ni semidúplex";
$perms = "Semidúplex";
$permd = "Dúplex";
$permsd = "Semidúplex y Dúplex";
$nomarch = "Terminales_Comdes";
$h1passw = "Error: contraseña caducada";
$errpassw = "Su contraseña ha caducado y debe actualizarla con los datos que le ha facilitado la Oficina COMDES";
?>
