<?php
/*
 * Textes en valencià per a terminales.php
 */

$titulo = "Base de Dades de Terminals de la Xarxa COMDES";
$termcomdes = "Terminals";
$h1 = "Terminals de la Xarxa COMDES";
$criterios = "Criteris de Selecció/Busca";
$resetcrit = "Netejar Criteris";
$provtxt = "Proveïdor";
$newtab = "Obrir en una nova pestanya";
$tipotxt = "Tipus de Terminal";
$fijo = "Fix";
$movil = "Mòbil";
$movilb = "Mòbil Bàsic";
$movila = "Mòbil Avançat";
$movilg = "Mòbil Gateway/ Repeater";
$portatil = "Portàtil";
$portatilb = "Portàtil Bàsic";
$portatila = "Portàtil Avançat";
$portatilx = "Portàtil ATEX";
$despacho = "Despatx";
$estadotxt = "Estat";
$alta = "Alta";
$baja = "Baixa";
$rep = "Reparació";
$txtaut = "Autenticació";
$dotstxt = "Alta en els DOTS";
$llamtxt = "Telefonades individuals";
$llamop2 = "Semi-dúplex";
$llamop3 = "Dúplex";
$llamop4 = "Ambdós";
$h4res = "Resultat de la busca";
$nreg = "Núm. total de registres";
$regpg = "registres per pàgina";
$todos = "Tots";
$detalle = "Detall";
$issiselec = "ISSI seleccionats";
$pgtxt = "Pàgina";
$newter = "Nou Terminal";
$noreg = "No hi ha registres";
$campos = array("Flota","Marca","Model","Tipus","Proveïdor","ISSI","TEI","Mnemònic","Carpeta","Tel. Ind.","DOTS","Aut.","Encriptat");
$thnterm = "Número de Terminals";
$thrango = "Rang d'ISSI";
$thllamind = "Tel. Ind.";
$thnserie = "N. Sèrie";
$thmodelo = "Model";
$thtipo = "Tipus";
$thmnemo = "Mnemònic";
$thaut = "Autenticació";
$thenc = "Encripitació";
$thdirip = "Adreça IP";
$thversion = "Versió";
$thfalta = "Data Alta";
$thfecha = "Data";
$thobserv = "Observacions";
$thnumk = "Número K";
$thprov = "Proveïdor";
$thcodhw = "Codi HW";
$txtdescarga = "Descarregar tots";
$permno = "ni dúplex ni semidúplex";
$perms = "Semidúplex";
$permd = "Dúplex";
$permsd = "Semidúplex i Dúplex";
$nomarch = "Terminals_Comdes";
$h1passw = "Error: contrasenya caducada";
$errpassw = "La seua contrasenya ha caducat i ha d'actualitzarla amb les dades que li ha facilitat l'Oficina COMDES";
?>
